from __future__ import annotations

from typing import List


MOCK_JOBS: List[dict] = [
    {
        "company": "토스",
        "title": "Backend Engineer",
        "location": "서울 강남",
        "source": "Wanted",
        "url": "https://toss.im/career",
        "salary_min": 6200,
        "salary_max": 7600,
        "rating": 4.5,
        "review_summary": "제품 속도는 빠르지만 높은 자율성과 책임이 요구됨",
        "skills": ["Java", "Kotlin", "Spring Boot", "Redis", "AWS"],
    },
    {
        "company": "카카오뱅크",
        "title": "서버 개발자",
        "location": "성남 판교",
        "source": "Wanted",
        "url": "https://www.kakaobank.com/Careers",
        "salary_min": 5800,
        "salary_max": 6900,
        "rating": 4.2,
        "review_summary": "금융 도메인 경험을 쌓기 좋고 조직 안정성이 높음",
        "skills": ["Java", "Spring Boot", "JPA", "Kafka", "MySQL"],
    },
    {
        "company": "당근",
        "title": "백엔드 소프트웨어 엔지니어",
        "location": "서울 서초",
        "source": "Wanted",
        "url": "https://about.daangn.com/jobs/",
        "salary_min": 6500,
        "salary_max": 7800,
        "rating": 4.4,
        "review_summary": "사용자 중심 문화와 빠른 서비스 실험이 강점",
        "skills": ["Kotlin", "Spring Boot", "Redis", "Kubernetes", "AWS"],
    },
    {
        "company": "컬리",
        "title": "플랫폼 백엔드 개발자",
        "location": "서울 강남",
        "source": "Wanted",
        "url": "https://careers.kurly.com/",
        "salary_min": 5600,
        "salary_max": 6600,
        "rating": 3.9,
        "review_summary": "물류와 커머스 문제를 다루며 운영 강도가 있는 편",
        "skills": ["Java", "Spring", "Redis", "MySQL", "Docker"],
    },
    {
        "company": "직방",
        "title": "Backend Developer",
        "location": "서울 강남",
        "source": "Wanted",
        "url": "https://www.zigbang.com/recruit",
        "salary_min": 5400,
        "salary_max": 6200,
        "rating": 3.8,
        "review_summary": "도메인 명확성이 높고 중견 조직 흐름을 경험하기 좋음",
        "skills": ["Java", "Spring Boot", "JPA", "AWS", "PostgreSQL"],
    },
    {
        "company": "오늘의집",
        "title": "시니어 백엔드 엔지니어",
        "location": "서울 서초",
        "source": "Wanted",
        "url": "https://bucketplace.career.greetinghr.com/",
        "salary_min": 6300,
        "salary_max": 7400,
        "rating": 4.1,
        "review_summary": "트래픽 규모와 조직 협업 경험을 쌓기 좋은 환경",
        "skills": ["Java", "Spring Boot", "Kotlin", "Redis", "Docker"],
    },
    {
        "company": "무신사",
        "title": "백엔드 개발자",
        "location": "서울 성수",
        "source": "Wanted",
        "url": "https://www.musinsa.com/app/corporate/recruit",
        "salary_min": 5700,
        "salary_max": 6800,
        "rating": 4.0,
        "review_summary": "커머스 데이터와 대규모 이벤트 대응 경험이 쌓임",
        "skills": ["Java", "Spring Boot", "JPA", "Redis", "Kafka"],
    },
    {
        "company": "버킷플레이스",
        "title": "Platform Backend Engineer",
        "location": "서울 강남",
        "source": "Wanted",
        "url": "https://bucketplace.career.greetinghr.com/",
        "salary_min": 6100,
        "salary_max": 7200,
        "rating": 4.3,
        "review_summary": "기술 스택 현대화가 잘 되어 있고 협업 밀도가 높음",
        "skills": ["Kotlin", "Spring Boot", "AWS", "Redis", "Terraform"],
    },
]
